### ISSUE TITLE
output didn't found for alias:

### ISSUE THREAD

**Issue by anibal-aguila** [rzkmak/newspopper#1]
Hi, I get this message:

```
output didn't found for alias:
```

my initial sites.yaml file content is:

```
port: 8080 #if not set, it will randomly generated with range (30000-39999)
backend:
  redis:
    uri: "localhost:6379"
    persist_duration: "336h" # 2 weeks, if not set will be default (1 week)

credential:
- type: "telegram"
  token: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  alias: "telegram_credential_001"

output:
- type: "telegram-channel"
  credential: "telegram_credential_001"
  channel: "@somename"
  alias: "your_channel.out"
# - type: "webhook"
#   url: "https://your-webhook.com/webhook-endpoint"
#   alias: "your_webhook"

listener:
# - type: "scrapper"
#   url: "https://your-website.com"
#   interval: 1m
#   selector:
#     main: ".main"
#     title: ".title"
#     link: ".link"
#   optional_http_code: 500
#   target: "your_channel.out"
- type: "rss"
  url: "https://lorem-rss.herokuapp.com/feed?unit=second&interval=30"
  interval: 1m
  target: ""
  format: "json"
# - type: "webhook"
#   url: "/update-event"
#   target: "your_channel.out"
```
